# Generated by Django 5.0.7 on 2024-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="networknode",
            options={"verbose_name": "Узел сети", "verbose_name_plural": "Узлы"},
        ),
    ]
