# Generated by Django 5.0.7 on 2024-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0002_product_alter_networknode_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                related_name="network_nodes", to="retail_network.product"
            ),
        ),
    ]
