# Generated by Django 5.0.7 on 2024-07-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0003_networknode_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
