# Generated by Django 5.0.7 on 2024-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0005_alter_networknode_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                related_name="network_nodes", to="retail_network.product"
            ),
        ),
    ]
