# Generated by Django 5.0.7 on 2024-07-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0007_alter_networknode_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="network_nodes", to="retail_network.product"
            ),
        ),
    ]
