# Generated by Django 5.0.7 on 2024-07-25 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_network", "0008_alter_networknode_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
